require: rubocop-rails

AllCops:
  Exclude:
    - bin/*
    - db/schema.rb
    - node_modules/**/*
    - vendor/**/*

Metrics/LineLength:
  Max: 120

Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb # Long blocks are inherent to the RSpec DSL

Metrics/MethodLength:
  Exclude:
    - db/migrate/* # Migrations are clearer defined as a single large method.